[theme]
base="dark"
primaryColor="#22c55e"         # accent color (green example)
backgroundColor="#0b1220"      # page background
secondaryBackgroundColor="#1a1f2e" 
textColor="#ffffff"
font="sans serif"
