SUPABASE_URL = "https://hldlwmbnjpzztjznowez.supabase.co"

# ⚠️ service_role key has full access — use only in server-side code
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhsZGx3bWJuanB6enRqem5vd2V6Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NTc5MTU2NywiZXhwIjoyMDcxMzY3NTY3fQ.CScS7gAjad1ddkSwP8c_z6_Xw1zsSEUNyd2FZL-NuxA"

# optional flag we used in the code switch
USE_SUPABASE = true

[keys]
GEMINI_API_KEYS = [
  "AIzaSyDTQiDEOd2OTKt3Ga_JaCJ4qy2M8BseKZ8",
  "AIzaSyA9851iq5W3-rk7TiZb3hBCZvZ3E2gu1wU",
  "AIzaSyBuC7zXGmi2_yVcx3KQw7EaMcE4KJYP9sg",
  "AIzaSyDuDv0drc5hS1djAOKhz93F4eRSBa5ZynU"
]